### ISSUE TITLE
Suggestion: Create a Nuget package for use in F# scripts

### ISSUE THREAD

**Issue by njlr** [RussBaz/WebFrame#1]
e.g.

```fsharp
// QuickServer.fsx

#r "nuget: WebFrame"

open WebFrame

[<EntryPoint>]
let main _ =
    let app = App ()
    
    app.Get "/" <- fun serv -> serv.EndResponse "Hello World!"
    
    app.Run ()
    
    0 // return an integer exit code
```

Then `dotnet fsi ./QuickServer.fsx`

**Comment by RussBaz** [comment]
I just wasn't sure that the project is stable enough to publish on nuget. Do you think it will be ok to do so even if it keeps changing its api?

**Comment by AngelMunoz** [comment]
relevant, it won't run on scripts until https://github.com/dotnet/fsharp/issues/8688 is done due how aspnet is included in the sdk

but I do agree having a pre-release nuget would help to get some users into testing this :)

**Comment by RussBaz** [comment]
I've just published the first test release of the framework. I will check if everything works as expected later. Docs and samples would need to be updated too.

**Comment by RussBaz** [comment]
All but the scripting seems to be working well now. The scripting with the ASP.NET Core is very broken indeed. I do not think I can do much at the moment.

If there is no workaround for SDK referencing in the scripts, then I will be closing this issue soon.

If one is found or dotnet finally allows SDK referencing in fsi, then I will reopen this issue once again.
